### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jombie** [davideas/FlexibleAdapter#472] opened 2017-10-20 09:50 UTC
Is it possible to add support for datasource from realm db.

It would be great to use live notification and dataset changes from realm & update the adapter accordingly.

**Comment by davideas** [comment] 2017-10-20 16:26
Duplicate of #166.

Regarding Live notification I'm working on LiveData integration (branch **live_data**) with Android Arch library and I will publish an alpha version of this new extension together with RC3 release.

**Closed by davideas** 2017-10-20 16:26 UTC
