### ISSUE TITLE
Animation not working on sticky header  when we try to add fadein effect when change background for new sticky header position with Change listener.

### ISSUE THREAD

**Issue by athul131** [davideas/FlexibleAdapter#587] opened 2018-04-08 11:16 UTC
Please help me resolve this ASAP.

Task:
Set a background image for sticky header.
When a new sticky header comes(Using OnStickyHeaderListener) the background need to be set with Animation like fade in etc.
Animation code not working for Sticky header but works fine for normal headers.

Any help would appreciated for this issue.

**Comment by davideas** [comment] 2018-04-10 18:03
Duplicate of #582.

**Closed by davideas** 2018-04-10 18:03 UTC
Labels: duplicate
