### ISSUE TITLE
Crash with FlexibleItemAnimator

### ISSUE THREAD

**Issue by SamYStudiO** [davideas/FlexibleAdapter#474] opened 2017-10-20 11:56 UTC
Using support 26+ when trying to add Animation to my list i  got this error
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
using
`mList.setItemAnimator( new FlexibleItemAnimator( ) );`

**Comment by davideas** [comment] 2017-10-20 16:06
Duplicate of #437, will be part of RC3 release soon.

But thanks for notifying.

**Closed by davideas** 2017-10-20 16:06 UTC
