### ISSUE TITLE
Sticky Header is not updating when updateDataSet.

### ISSUE THREAD

**Issue by krupalagile** [davideas/FlexibleAdapter#500] opened 2017-11-28 13:55 UTC
Version : 5.0.0-SNAPSHOT 
Sticky Header is not updating when `updateDataSet `is called.
`onBindViewHolder `is not called.
After scrolling some items, it gets called.

**Comment by davideas** [comment] 2017-11-28 13:59
@krupalagile, do you use stableIds and correctly implemented equals? it might depends by that.

**Comment by krupalagile** [comment] 2017-11-29 08:47
I have passed false in hasStaleIds in FlexibleAdapter constructor.

**Comment by krupalagile** [comment] 2017-11-29 12:13
The problem occurs when headers are expandable and sticky at the same time.

**Comment by davideas** [comment] 2017-11-29 12:59
Duplicate of #499.

**Closed by davideas** 2017-11-29 12:59 UTC
