### ISSUE TITLE
Automatic sticky header view draws over fastscroller

### ISSUE THREAD

**Issue by magneticflux-** [davideas/FlexibleAdapter#497] opened 2017-11-26 02:17 UTC
Because the automatically created sticky header layout is added to the end of the RecyclerView's parent, it is drawn after the fastscroller (added in XML after the RecyclerView) is drawn. This causes the fastscroller's bar and bubble to be cut off by the sticky header.

To work around this, I use this line of Kotlin code:
```Kotlin
fast_scroller.post { fast_scroller.bringToFront() }
```
Equivalent Java code:
```Java
fastScroller.post(() -> fastScroller.bringToFront());
```

That code runs after the sticky header view is created and added and it forces the fastscroller to be above all views in the layout (the desired behavior).

Version: 5.0.0-rc3

**Comment by davideas** [comment] 2017-11-28 08:28
Duplicate of #446.

**Closed by davideas** 2017-11-28 08:28 UTC
Labels: duplicate
