### ISSUE TITLE
Sticky headers without sub items and non-sticky headers with sub items

### ISSUE THREAD

**Issue by maltebucksch** [davideas/FlexibleAdapter#209] opened 2016-10-20 07:07 UTC
This is either a bug or not very well documented topic in the wiki.

The problem: I have multiple instances of subclasses of AbstractExpandableHeaderItem in my recyclerview.
Some of the headers have sub items and some are just headers to divide different areas in the view (without sub items - I will call them AreaHeader here).

What I want: I want the "AreaHeaders" to be sticky BUT the sub headers (which have sub items attached and extends AbstractExpandableHeaderItem) to be NON-sticky.

What I have right now (after trying around for a long while without success):
1. I have sticky headers for all headers that have subitems: I tried to pass false in their view holder to the parent to disable this but it does not work:
`HeaderViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter,false);
 }`
2. My headers just don't want to be sticky for the AreaHeaders:
I tried to extend AbstractFlexibleItem while implementing IHeader. I tried to extend AbstractExpandableHeaderItem. As long as I don't add sub items to these headers they won't be sticky.

I use a SmoothScrollGridLayoutManager. This is how I set up the adapter:
`adapter.setLongPressDragEnabled(true)
                .setDisplayHeadersAtStartUp(true)
                .expandItemsAtStartUp()
                .enableStickyHeaders();`

My question: 
1. How do I make headers without sub items sticky?
2. How do I make headers with sub items NON-sticky?

I use flexibleAdapter a lot, and I would really appreciate your help on this issue. thanks in advance.

**Comment by davideas** [comment] 2016-10-20 12:31
@maltebucksch, it's not a bug, neither a lack of docs. You want something particular!

I never tried but in theory this should work: You can have only one `IHeader`, assigned to the item that must remain sticky (yours `AreaHeader`); Regarding the expandable (parent), it is an `ISectionable` + `IExpandable` where you pass the header item and the subItems.
The subItem is just normal item that inherits from `IFlexible` (you can use `AbstractFlexibleItem`).

For the couple `ISectionable` + `IExpandable` probably you can still use `AbstractExpandableItem` but you need to implement `ISectionable`. Basically you need to create a `AbstractExpandableSectionableItem` -> the parent expandable is not an header!

- Setting false it doesn't help because that is dedicated to the ViewHolder that wraps the layout with a FrameLayout and avoids the ClassCastException, so keep it true.
- It's obvious that if another IHeader is preceded by an IHeader, then the sticky container swaps the headers.

**Comment by maltebucksch** [comment] 2016-10-25 13:46
@davideas 
Thanks for your quick feedback. I removed the extension of IHEader in all Items but the AreaHeader and added one child to make it sticky. Works like a charm now. 
In the docs it is not explained when exactly headers stay sticky and when not. That's why I considered it a missing part there.

**Comment by davideas** [comment] 2016-10-26 07:26
@maltebucksch, very good.
But you really didn't understand that only the `IHeader` object can stay sticky and that if you apply this interface to others, all works as header?

**Closed** 2016-12-20 21:40 UTC
Labels: question
