### ISSUE TITLE
Issues with sticky header

### ISSUE THREAD

**Issue by ILikeYourHat** [davideas/FlexibleAdapter#320] opened 2017-03-17 08:16 UTC
Hi,
I have some problems with the sticky header feature, used together with expand/collapse behavior

1. Sometimes the sticky header view losses it's background. It's nearly impossible to provide steps to reproduce this, you need just to drag, expand and collapse random list headers for a while.

2. Sometimes the sticky header is not shown correctly. Steps to reproduce:
- make an sticky adapter with 3 expandable headers, 10 children each
- make them collapsed on start
- on the top of the list, expand the second one, then the first one
- scroll down until you reach the second header, scroll a bit more, so that the bottom of sticky header is in the middle of the first item, collapse header
- scroll up, the sticky header is missing at this point

3. How to handle expand state change properly? I have an arrow at the header item, it should rotate when this state changes. I'm updating this when binding view holder, and in expandView/collapseView methods in the view holder. Still, sometimes the arrow have wrong rotation, should i override any other method to handle it properly?

**Comment by davideas** [comment] 2017-03-19 13:55
@ILikeYourHat, could you please check if those issues are still present when you use the Snapshot version? Have a look at the last post of #39.

**Comment by ILikeYourHat** [comment] 2017-03-19 19:38
2 and 3 are still present, for 1 I've found a workaround (wrapping item with FrameLayout), so I am not sure. I will check this tomorrow and let you know

**Comment by ILikeYourHat** [comment] 2017-03-20 14:18
Yup, 1 is present too.

**Comment by pkleczko** [comment] 2017-03-20 15:30
Hi, I also face issue 2 with disapearing sticky header when you collapse it after you scrolled its section up and  down.
1) Expand sections
2) Scroll up till section B become sticky
3) Scroll a litte down
4) Collapse section B
Sticky header for section B disaapeares.

Any fix for this issue would be very helpful.

**Comment by davideas** [comment] 2017-03-22 15:39
@ILikeYourHat, @pkleczko, thanks, I will verify the issues n.1-2. Unfortunately, I am quite busy on something else more urgent than this.

@ILikeYourHat Regarding the point 3) you should call `isExpanded()` when the item is bound (in `bindViewHolder`). You can enable the automatic rebound of the expandable by overriding `ExpandableViewHolder.shouldNotifyParentOnClick()` please check [ExpandableHeaderItem](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/items/ExpandableHeaderItem.java).

Thanks to an older issue, I've also done a fix if automatic collapse all is enabled too (available for the moment only in the Snapshot version).

**Comment by davideas** [comment] 2017-03-22 16:20
For point 2) I got illumination, basically, the issue derives from the technical scrolling when items disappear... To fix, temporary override collapseView until I publish the snapshot as following:

``` java
@Override
protected void collapseView(int position) {
	super.collapseView(position); //If overridden, you must call the super method
	if (itemView.getX() < 0 || itemView.getY() < 0) {
		mAdapter.getRecyclerView().scrollToPosition(position);
	}
}
```
If you have a better idea please advice.

But this introduce another little glich: basically scroll to have the sticky header (B) almost to the end of child 2. Then you expand, sometimes you will see the sticky header not at the correct position, it will restore the position as soon as you scroll 1 pixel.

**Comment by volser** [comment] 2017-03-31 15:14
After refresh data, if header item is partially visible, then sticky header not sticked.
https://youtu.be/meu3rq2V5aY

in demo project original item is visible, in my just blank place

**Comment by volser** [comment] 2017-03-31 15:38
how to reproduce: swipe to refresh and scroll up in a half of item height (see video)

**Comment by davideas** [comment] 2017-04-10 21:24
@volser, that half item scroll while you refresh might be the touch of your finger. If I refresh the list it doesn't occur, but I'm using the latest code from Snapshot. Just published the new App from Snapshot under [latest release](https://github.com/davideas/FlexibleAdapter/releases).

@ILikeYourHat, the solution proposed nicely fix the behaviour in point 2) but it introduces an issue which is worst than the previous, as described. However, the fact that some items scroll out of the screen is managed by LayoutManager when it recalculate the items to contain. So I do not consider it as bug.

For point 3, please use the current Snapshot, you can now be sure an item receives the update or not. However, you should read the property by calling the method `isExpanded()` in the item implementation, ?_which is the one I use in my example_. If you refer to a sticky item **that remains sticky**, I temporary disabled the rebound because of a possible crash. Need to find another way to propagate the new content.

For pont 1, I do know how much realistic the mechanism to reproduce is for the final user.

**Comment by davideas** [comment] 2017-04-12 21:43
@ILikeYourHat, probably I found the way to reproduce the point 1).
Using the UNDO feature when retrieving the next sticky header, the position of the first visible item is wrong. As from official documentation:
> This position does not include adapter changes that were dispatched after the last layout pass.

So, RV thinks that header is swapped, while it isn't, because the situation is still not changed after the delete notifications are dispatched.
I now added a delay of 100ms after any dispatch, and at least this issue should be resolved.

I will deploy in the next snapshot.

**Comment by ILikeYourHat** [comment] 2017-04-13 07:53
Great, thank you :) So, for clarity (correct me if I am wrong):
1. It will be fixed in the new snapshot
2. It is fixed, but that fix introduces a small bug, and that small bug cannot be fixed because Android
3. It is already fixed

**Comment by davideas** [comment] 2017-04-15 19:29
@ILikeYourHat, snapshot published.
1) Give a try, not sure if it is the same issue.
2) I've put that fix in the snapshot, please give some tries, now it seems to work better. Anyway, if the bug described [here](https://github.com/davideas/FlexibleAdapter/issues/320#issuecomment-288454124) appears, I do not know how to resolve it.
3) Not a bug for me.

**Comment by davideas** [comment] 2017-04-24 18:01
@ILikeYourHat, if you don't have other remarks on this fix, I will close this issue.

**Closed** 2017-05-03 16:12 UTC
Labels: bug, resolved
