### ISSUE TITLE
Inconsistency detected.

### ISSUE THREAD

**Issue by steff-maya** [davideas/FlexibleAdapter#411] opened 2017-07-13 14:32 UTC
Process: eu.davidea.samples.flexibleadapter, PID: 6175
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 233(offset:-1).state:476 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:

**Comment by davideas** [comment] 2017-07-13 14:42
@steff-maya, I cannot help if you don't give any specification, the issue template is there for a reason.
Please, tell in which situation you experimented that occurs and which method you are calling, which version you are using, If this occurs often.
Finally, if you have already analyzed something by enabling adapter logs.

**Comment by steff-maya** [comment] 2017-07-13 15:09
I was testing the demo of the library in the section called "expandable section" then just scroll very fast an touch some item, when suddenly the app stoped and the logs show the following error :

Process: eu.davidea.samples.flexibleadapter, PID: 6175
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 233(offset:-1).state:476 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:

I was testing on a Lg-k-350 Api 23

**Comment by davideas** [comment] 2017-07-13 15:26
@steff-maya, thanks.
Now, if you also are able to explain how to reproduce it, because I tried but I was not "lucky" as you :-)

**Comment by davideas** [comment] 2017-07-25 07:29
If you don't have any update, I will close this issue.

**Closed** 2017-07-27 07:33 UTC
Labels: invalid

**Comment by Akhil-Tripathi** [comment] 2017-09-04 18:15
@davideas got the same crash,
not reproducible 
Logs : java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:2).state:2
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5512)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5448)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5444)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3551)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3030)
                                                                          at android.view.View.measure(View.java:21998)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:21998)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:652)

**Comment by davideas** [comment] 2017-09-08 14:22
@Akhil-Tripathi, @steff-maya, normally if the LayoutManager is busy with something and a change in the list occurs, that could be the cause! Give some time to the LayoutManager, use postDelay.
All happens in few milliseconds so, control with operation you were doing before seeing the crash.

This is all I can say.

**Comment by Akhil-Tripathi** [comment] 2017-09-12 10:48
@davideas https://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position

go through this thread... it fixed my crash...

Let me know if any consequences

**Comment by davideas** [comment] 2017-09-12 15:43
@Akhil-Tripathi, I've read many things/solutions there, many are not ok! Now, I don't know which one you adopted, but if you didn't read the wiki page [Update Data Set](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Update-Data-Set), better to read it now.
