### ISSUE TITLE
Item content not updating when animating updateDataSet

### ISSUE THREAD

**Issue by henengel** [davideas/FlexibleAdapter#377] opened 2017-05-29 09:43 UTC
Hi David, how are you :) ?
I think I found a bug/issue that was supposed to be fixed, but still isn't.
I read in this repository issues several tickets (#210...) that resemble mine,  not sure if related.

Issue: 
When updating the dataset with adapter.updateDataSet(new ArrayList<>(items), true), the content of the items don't update.

Used code:
```java
 private void initFeed() {
        /* Get recyclerView from layout */
        mRecyclerView = (RecyclerView) getView().findViewById(R.id.recyclerViewMain);

        /* Save views to cache to prevent reload of them*/
        mRecyclerView.setItemViewCacheSize(80);
        mRecyclerView.setHasFixedSize(true);

        /* Create the adapter */
        mAdapter = new FlexibleAdapter<>(new ArrayList<>(mResults));

        /* Create pre cache layout manager to load views before displayed to user */
        PreCachingLayoutManager layoutManager = new PreCachingLayoutManager(mContext, GeneralUtils.getInstance().getScreenHeight() * 2);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        mRecyclerView.setLayoutManager(layoutManager);

        /* Set adapter */
        mRecyclerView.setAdapter(mAdapter);

        /* Set StickyHeaders */
        mAdapter.setDisplayHeadersAtStartUp(true).setStickyHeaders(true);
    }
```

```java
public void onDataChange(final ArrayList<IFlexible> newResults) {

        /* Save scroll position */
        Parcelable recyclerViewState;
        recyclerViewState = mRecyclerView.getLayoutManager().onSaveInstanceState();

        mAdapter.updateDataSet(newResults, true);

        /* Restore scroll position */
        mRecyclerView.getLayoutManager().onRestoreInstanceState(recyclerViewState);

        /* Set new results to default */
        mResults = newResults;
    }
```

Solutions tried:
1. I changed the dependency to your snapshots (where if I understood correctly this issue was supposed to be fixed):

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
    maven {url = "https://oss.sonatype.org/content/repositories/snapshots/" } //For Snapshots
}

dependencies {
...
compile 'eu.davidea:flexible-adapter:5.0.0-SNAPSHOT'
}
Didn't help...

2. Tried 
`mAdapter.updateDataSet(newResults, true); `/ `mAdapter.updateDataSet(new ArrayList<>(newResults), true);` - didn't work

Anything else I can do/try to solve this?
Thank you

**Comment by davideas** [comment] 2017-05-29 10:35
@henengel, I'm ok thanks.

Currently, to enable changes there's this method `setNotifyChangeOfUnfilteredItems()` that works for update and filter, because both use same process. This property is disabled by default, _should it be enabled by default?_
Relevant code [FlexibleAdapter.java#L4456](https://github.com/davideas/FlexibleAdapter/blob/current_snapshot/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L4456).

I've also reviewed the wiki page [updateDataSet](../wiki/5.x-%7C-Update-Data-Set) on the last weekend for RC2 where I explain how to update content.

**Comment by henengel** [comment] 2017-05-29 12:46
@davideas 
In my opinion, of course, the default should be true.
Most people expect all data to be updated when updating the data set.
Those who have large lists are unusual and should seek the configuration the fits them.
Thank you

**Comment by davideas** [comment] 2017-05-29 12:48
@henengel, thanks for your opinion.

**Comment by henengel** [comment] 2017-05-29 12:49
Thank you for your help!

**Comment by henengel** [comment] 2017-05-31 15:09
@davideas Hi David,
Wanted to let you know that there are still bugs when using `setNotifyChangeOfUnfilteredItems()`.
When using this setting, the feed items get messed up, in their position and content.
From what I experienced, if you:
1. Load the same dataset. 
2. Change the content items.
3. In 2 different sessions one with `setNotifyChangeOfUnfilteredItems(true)` and `updateDataSet(items, true)` set, and the other without those settings set.
4. Then update the dataset, you will see different results.

**Comment by davideas** [comment] 2017-05-31 17:41
@henengel, change the content items in which ways? you mean delete/add/change and update with true, restarting the test with same delete/add/change and update with false the positions are different?

**Comment by henengel** [comment] 2017-05-31 19:15
@davideas 
What I mean with change content is, in my case I have articles as items. their title, subtitle, image, comments(displayed as a number of comments), and time of articles.
When I `updateDataSet(items, true);` and `setNotifyChangeOfUnfilteredItems(true);`, The contents of the articles get mixed up. the image from one article appears in another, the order of the articles change even though they weren't changed in the dataset. (I can't tell if the articles move position, might be only there content is mixed up with contents of another article).
I will try and generate 2 short videos for you to see.

**Comment by magneticflux-** [comment] 2017-05-31 19:25
@henengel Are you implementing `.equals()` and `.hashCode()` for your objects? A reproducible test case 
 with the minimum code to trigger the problem would be a huge help too.

**Comment by davideas** [comment] 2017-05-31 19:27
@henengel, I made a new unit test on that, maybe the test case is not the same as you mean, or maybe the test is wrong, but for me the 2 lists in the tests are equals with items at the same position.

**Comment by henengel** [comment] 2017-05-31 19:33
> Are you implementing .equals() and .hashCode() for your objects? A reproducible test case
I am...

I would pursue items getting wrong info updated then moving position.
As I said I only noticed the issue while testing my app for releasing a new build.
I have to get past this release and in the next one I would like to integrate the animation, hence I will be checking everyhting again.
When I encountre it again, I'll try to generate 2 short videos and see if I can reproduce any test case.
As I said it doesn't happen everytime and I can't seem to trigger the issue all the time. I'll try my best to provide more info soon once I start testing again...

**Comment by davideas** [comment] 2017-05-31 19:55
I've reviewed the specific unit test, now it's better.

**Comment by henengel** [comment] 2017-06-01 06:13
@davideas I have been testing again after your last comment and seems to be working ok.
I'll continue testing and ping you if I encounter any problem.
One last question if I may,
If using your dependency `compile 'eu.davidea:flexible-adapter:5.0.0-SNAPSHOT'`, is the code received in the app modified remotely by you?
I need to release a new version of my app, and of course, I can't take the risk of something changing in the code remotely.

**Comment by davideas** [comment] 2017-06-01 10:08
@henengel if you prepare the apk, whatever is built into, it remains. The snapshot library is indeed update automatically at every my publication and affects the current build. You can always make a copy of the library file.

However, I'm awating few tasks here to be resolved in order to publish the RC2 so those will be included (included the new `FlexibleItemDecoration`). I won't publish again the snapshot.

**Comment by henengel** [comment] 2017-06-01 22:16
@davideas 
Hi David, sorry to say that the issue still remains. the first item in my data set after updating (sometimes), suddenly appears around position 5-10. Also, the first article has comments, and after updating the comments disappear.
I can't seem to trigger the issue or understand when or why it happens. could be some of the items have updated (I have around 60 so it's hard to say). but I'm sure of the position of the item. In the dataset, it appears first, and in the app, it doesn't.
Also, I can't provide you with specific code to reproduce the issue since there is a lot going on there and I'm not sure what is relevant and what isn't.
If you would like, I don't mind sharing the project with you, for you to take a look. You probably know better for what to look for, and know better how to find it.

**Comment by davideas** [comment] 2017-06-02 07:52
@henengel, let's resolve this, I will debug that process and verify what's going on. Explain me what to touch in order to trigger that update in your app.

**Comment by henengel** [comment] 2017-06-02 10:26
@davideas 
I added you as a collaborator in the project.
To try in reproduce the problem, all you need to do is swipe to refresh.
I recommend leaving the app in background for several minutes, and then updating.
If you have any question, need more info from me, feel free to contact me here, or skype: chen_engel, or any other platform that you prefer.
As far as time difference (although I work a lot :) ), I'm on GMT +2, take that into consideration. 
I'll try to be as available for you as I can.

**Closed** 2017-06-10 21:56 UTC
Labels: enhancement

**Comment by henengel** [comment] 2017-06-11 22:00
Hi David, how are you.
So I have been testing everything, and so far so good.
If I will encounter anything, I'll let you know.
Thank vary much for your help and time spent helping me.
Much appreciated.
Regards,
Chen
