### ISSUE TITLE
Can I remove duplicates from adapter data ?

### ISSUE THREAD

**Issue by uddyami** [davideas/FlexibleAdapter#453] opened 2017-09-20 21:09 UTC
I'm getting stuck where i see duplicate data as well as duplicate headers.. Any ideas how i can keep data clean ?

**Comment by davideas** [comment] 2017-09-20 21:13
@uddyami, if you don't add headers in the list you provide to the Adapter, but let the Adapter to manage them with setDisplayHeadersAtStartUp/showHeaders/hideHeaders, you won't have duplicates.

Duplicate data can also be caused by a not well implementation of the `equals` method.
All this is explained in the wiki page dedicated for the headers and sections.

**Comment by davideas** [comment] 2017-09-22 14:12
Let me know if you have still troubles, showing something, otherwise, I will close this issue.

**Closed** 2017-09-27 08:56 UTC
Labels: support
