### ISSUE TITLE
Drag&Drop in GridLayout leads to items switching sections randomly

### ISSUE THREAD

**Issue by maltebucksch** [davideas/FlexibleAdapter#148] opened 2016-07-21 17:07 UTC
This bug is also visible in the demo app.
I am using SmoothScrollGridLayoutManager with headers to seperate item groups. 

If you drag an item (AbstractFlexibleItem) from one area (seperated by header) to another neighbour area (section), then: In addition to the focused item -> often another item teleports underneath the header/to the other section.

To reproduce: 
1. Open "Headers and sections" example
2. Switch to gridlayout
3. Drag modules from one section to other sections (up and down). 
Quickly some modules switch section although you have not moved them to another section.

I am expecting items only to move to another section if I drag them to there. No item should go to another section if not in DRAGGING state. The automatic reordering of items should not happen across sections as it leads to the described bug.

I am using a Nexus 5X, Android 6.0.1. I use flexible adapter 5.0.0-b7.

It might be possible to prohibit items from moving sections if they are not in DRAGGING state? that would be my suggested workaround at least.

I really need this behavior to work correctly as I am integrating this library in a bigger project. A quick fix or work around would be appreciated a lot.

**Comment by davideas** [comment] 2016-07-21 17:46
Hi @maltebucksch, thanks for your message, indeed I've reproduced it but something else happens: since I call `Collections.swap()` the header takes the position of the item being dragged. Indeed, others items do not change header since if you display the current header as subtitle or do a refresh they still belongs to the correct header. It is just a visual effect.

Sincerely, I never tested the dragging with GridLayout, when I developed I focused on Linearlayout.
Now, for GridLayout, manual drag should be fixed.
Unfortunately, this is not easy to resolve.

I have already something in mind, need to check if there are more items after or before it, it depends by the dragging direction, finallym based on that make a "move` instead of "swap". Quite difficult...

**Comment by davideas** [comment] 2016-07-21 17:53
When I made `swapItems()` it took me quite long time... and still not finalized.
You can completely override this method and apply another solution:
``` java
public void swapItems(int fromPosition, int toPosition);
```
OR
you can also help me by rewriting that method and make a pull request.

**Comment by maltebucksch** [comment] 2016-07-22 05:07
Thanks for your quick replay @davideas. I see. 
Since I am not familiar with your library, it will probably take me some time to resolve that one.
But if I can get the time, I will gladly help resolving that one. In the mean time please keep me updated :-)

A workaround (which might look ugly, but works) would be fine, too. E.g. if it just refreshes the view or swaps back items if they have been misplaced. 

If that behavior works I can also gladly add the app of the company I am developing for to your example project list (in about 2.5 months)

**Comment by davideas** [comment] 2016-07-22 07:56
I've found something on Internet already done (why reinvent the wheel? :+1:).
I will start from here. Good news is that I tried and the visual movement are ok for me.
Basically for each middle item between the origin and target position, we also need to swap the middle items up or down by 1 position.

All the rest should be verified if it continues to work. As you know if an item is swapped it might change the section, so I already re-link the item with the new header and update the 2 header items so they are aware of the new number of items belonging to them.

**Comment by maltebucksch** [comment] 2016-07-22 14:05
That's great news, davideas, sounds like a neat solution! Any estimated time when you will integrate that in your library?

**Comment by davideas** [comment] 2016-07-22 19:13
@maltebucksch, I think I did it, for me is acceptable, it was quite easy eventually.

- When you confirm that this commit and the test you do resolve this issue, I will create the new Snapshot and the new apk. (Please use the current code in **dev** branch to generate and test the demoApp, not the published apk yet).

- Because I think you are the first one who use this feature, please test deeply.
I remind you that you can tune the velocity and other stuff from the callback, (I don't know how to use it, but I put the customizable anyway). So if you can tune them, and explain how they works 

- Moreover, I already had in mind to activate the new callback `shouldMove()` in `OnItemMoveListener` (now it's commented in the code), please let me know if that could be useful too, otherwise the method `shouldMove()` in the Adapter can be overridden already.

**Comment by maltebucksch** [comment] 2016-07-23 06:09
@davideas great, thanks for the quick actions from you side. I will definitely test it this week and come back to you with my observations.

**Comment by maltebucksch** [comment] 2016-07-23 09:54
Just tested it for a while. It works like a charm. "shouldMove" would definitely be great. I will make use of that feature for sure, so if there is a nice callback outside of the adapter for it, even better!

I will check out the velocity param when needed and buzz you when I understood their behavior.

As I will make extensive use of your gridlayout with sections implementation in the next months, I can keep you up to date with other issues I encounter. But for now it looks good.

**Closed** 2016-09-17 11:16 UTC
Labels: bug, resolved
